### PR TITLE
[6514] RTE: click the list button doesn't produce the list-unlist result in the Form Engine.

### PR DESCRIPTION
**Pull request by jvega190**
https://github.com/craftercms/craftercms/issues/6514

### CODE REVIEW

**Comment by jvega190** [comment]
@rart ^

**Review by rart — COMMENTED** [review]
@jvega190 what was the issue?

**Comment by jvega190** [comment]
@rart having the RTE content wrapped with elements like `h3` or `p` was causing the issues as other inline elements can't be inside those elements. By wrapping the RTE content in div (just as we have it in other bps) and moving the tags in the actual RTE content (again, just like in BPs like editorial) the issue doesn't happen anymore.

**Comment by rart** [comment]
Please confirm if this was an issue on previous versions.

**Comment by jvega190** [comment]
There are some issues in previous versions (adding ordered list ends up in unordered list, and some content issues too), but the unordered list/unlist does work

*Is this particular BP, not in general

**Review by rart — CHANGES_REQUESTED** [review]
Changing semantic elements like p and h3 for a div is not a good fix or something I'd be happy to recommend. We need should keep trying to better identify and explore better options.

**Comment by jvega190** [comment]
@rart I haven't found a solution yet. Though I found out that when the markup is like in this case (an `h3`), `editor.getContent({format: 'html'})` (link [here](https://github.com/craftercms/studio-ui/blob/develop/ui/guest/src/controls/rte.ts#L214)) doesn't return the markup, causing the list (in this scenario) to get lost. I'll continue investigating about this

**Pull request closed without merging**
